import { getAddress, type Address } from "viem";

/**
 * Top 150 arcade wallets, merged into hub GTD after contest close.
 *
 * Generated by `node scripts/export-arcade-gtd.mjs` (from web/). Do not hand-edit
 * the address list unless you are locking the export for the Friday redeploy.
 *
 * Frozen Fri Sep 18 2026 ~7:00 AM PT for GTD hub ship: live `/api/arcade/board`
 * was closed with `count: 0` / empty board (store=cache). Export list stays empty
 * — no arcade top-150 wallets to merge into GTD.
 */
export const ARCADE_GTD_REASON = "Arcade top 150";

/** Seed / export list — mixed-case 0x addresses are fine. */
export const ARCADE_GTD_WALLET_ADDRESSES = [] as const;

function checksum(address: string): Address {
  return getAddress(address.toLowerCase());
}

export const ARCADE_GTD_WALLETS: readonly Address[] =
  ARCADE_GTD_WALLET_ADDRESSES.map(checksum);

export const ARCADE_GTD_WALLET_SET: ReadonlySet<string> = new Set(
  ARCADE_GTD_WALLETS.map((address) => address.toLowerCase()),
);

export function isExportedArcadeGtdWallet(address: string): boolean {
  try {
    return ARCADE_GTD_WALLET_SET.has(checksum(address.trim()).toLowerCase());
  } catch {
    return false;
  }
}
